# Generated by Django 4.2.3 on 2025-08-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
                ("img", models.ImageField(upload_to="imgs/")),
                ("desc", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "上传文件",
                "db_table": "t_upload_file",
            },
        ),
    ]
