# Generated by Django 4.2.3 on 2025-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "co2",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="二氧化碳浓度"
                    ),
                ),
                (
                    "damp",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="湿度"
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="温度"
                    ),
                ),
                ("time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "t_client",
            },
        ),
    ]
