# Generated by Django 4.2.3 on 2025-08-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工具描述")),
                ("uurl", models.CharField(max_length=1000, verbose_name="跳转链接")),
            ],
        ),
    ]
