# Generated by Django 4.2.3 on 2025-07-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="课程分类名称")),
                (
                    "learn_info",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程学习信息"
                    ),
                ),
                (
                    "learn_style",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程学习方式"
                    ),
                ),
                (
                    "learn_time",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程学习时间"
                    ),
                ),
                (
                    "supervision",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程监督方式"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程分类图标"
                    ),
                ),
                (
                    "brief",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程分类简介"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(blank=True, null=True, verbose_name="课程分类级别"),
                ),
            ],
            options={
                "db_table": "t_course",
            },
        ),
    ]
