# Generated by Django 4.2.3 on 2025-08-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course_app", "0002_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="课程章节名称")),
                (
                    "level",
                    models.IntegerField(blank=True, null=True, verbose_name="课程章节级别"),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="course_app.stage",
                        verbose_name="课程阶段",
                    ),
                ),
            ],
            options={
                "db_table": "t_chapter",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="课程小节名称")),
                (
                    "is_must",
                    models.IntegerField(blank=True, null=True, verbose_name="是否必修"),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, null=True, verbose_name="课程时长"),
                ),
                (
                    "learned_count",
                    models.IntegerField(blank=True, null=True, verbose_name="学习人数"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程小节视频地址"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="course_app.chapter",
                        verbose_name="课程章节",
                    ),
                ),
            ],
            options={
                "db_table": "t_section",
            },
        ),
    ]
