# Generated by Django 4.2.3 on 2025-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="教师姓名")),
                (
                    "brief",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="教师简介"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="教师头像"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="教师职位"
                    ),
                ),
                (
                    "characteristic",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="教师特点"
                    ),
                ),
            ],
            options={
                "db_table": "t_teacher",
            },
        ),
    ]
