### 测试工具类
GET http://localhost:8000/tools/

### 测试
POST http://localhost:8000/tools/
Content-Type: application/json

{
    "name": "测试",
    "uurl": "www.baidu.com"

}

### 测试
DELETE http://localhost:8000/tools/1/
Content-Type: application/json

{
  "id":1
}