# Generated by Django 4.2.3 on 2025-08-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="年龄")),
                (
                    "sex",
                    models.IntegerField(
                        choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
                    ),
                ),
            ],
            options={
                "db_table": "t_student",
            },
        ),
    ]
