# Generated by Django 4.2.3 on 2025-07-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, null=True, verbose_name="手机号"),
                ),
                (
                    "_password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="真实密码"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "女"), (1, "男")],
                        default=1,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="职称"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, null=True, verbose_name="简介"),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="头像"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "db_table": "t_user",
            },
        ),
    ]
